apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: task-manager
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  sessionAffinity: None
